services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - wordle-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - wordle-net
    depends_on:
      - backend

networks:
  wordle-net:
    driver: bridge
