# Generated by Django 4.2.24 on 2025-09-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_mode',
            field=models.CharField(choices=[('single_player', 'Single Player'), ('multiplayer', 'Multiplayer')], default='multiplayer', max_length=20),
        ),
    ]
